### ISSUE TITLE
DLL？

### ISSUE THREAD

**Issue by Gaoyongxian666** [HaikuArchives/DOCTranslator#1]
hi，Can you package the project into dll? I want to use python to call it on the Windows platform, but I don't know how to convert the C file into dll

**Comment by scottmc** [comment]
maybe try https://pypi.org/project/antiword/
this is a translator for Haiku, no we won't be maybe a dll for windows.

**Comment by Gaoyongxian666** [comment]
I can't package programs on windows. How can I package this project?
![IMG_20221020_085236](https://user-images.githubusercontent.com/35163802/196831562-a2bd954d-8f33-47e6-b54b-c73ef46bbecb.jpg)

**Comment by scottmc** [comment]
Again, this is a program that will only work on Haiku (haiku-os.org)  If you are using Haiku, you can install Haikuporter and build the doctranslator recipe.  There's instructions on using Haikuporter in the haikuports github wiki.  If you are trying to use this in Windows, you're going to have a bad day.
